DOMAIN = "justwatch_streams"

CONF_PROVIDERS = "providers"
CONF_URL = "url"

DEFAULT_NAME = "JustWatch Streams"
JUSTWATCH_HOST = "justwatch.com"
SUBENTRY_FILM = "film"

PROVIDERS = {
    "all4": "Channel 4",
    "amazon_freevee": "Amazon Freevee",
    "apple_tv_plus": "Apple TV Plus",
    "ard_mediathek": "ARD Mediathek",
    "arte": "Arte",
    "bbc_iplayer": "BBC iPlayer",
    "britbox": "BritBox",
    "canal_plus": "Canal Plus",
    "crave": "Crave",
    "crunchyroll": "Crunchyroll",
    "dazn": "DAZN",
    "discovery_plus": "Discovery Plus",
    "disney": "Disney Plus",
    "filmstruck": "FilmStruck",
    "hayu": "Hayu",
    "hbo_max": "HBO Max",
    "hulu": "Hulu",
    "joyn": "Joyn",
    "magenta_tv": "MagentaTV",
    "mubi": "MUBI",
    "netflix": "Netflix",
    "now": "NOW",
    "paramount_plus": "Paramount Plus",
    "peacock": "Peacock",
    "plex": "Plex",
    "prime": "Prime Video",
    "rakuten_tv": "Rakuten TV",
    "rtl_plus": "RTL Plus",
    "sky_go": "Sky Go",
    "starz": "Starz",
    "wow": "WOW",
    "youtube_premium": "YouTube Premium",
    "zdf": "ZDF",
}

PROVIDER_ALIASES = {
    "all4": ("channel 4", "all 4"),
    "amazon_freevee": ("amazon freevee", "freevee"),
    "apple_tv_plus": ("apple tv plus", "apple tv+"),
    "ard_mediathek": ("ard mediathek", "ard"),
    "arte": ("arte",),
    "bbc_iplayer": ("bbc iplayer",),
    "britbox": ("britbox",),
    "canal_plus": ("canal plus", "canal+"),
    "crave": ("crave",),
    "crunchyroll": ("crunchyroll",),
    "dazn": ("dazn",),
    "discovery_plus": ("discovery plus", "discovery+"),
    "disney": ("disney plus", "disney+"),
    "filmstruck": ("filmstruck",),
    "hayu": ("hayu",),
    "hbo_max": ("hbo max", "max"),
    "hulu": ("hulu",),
    "joyn": ("joyn",),
    "magenta_tv": ("magentatv", "magenta tv"),
    "mubi": ("mubi",),
    "netflix": ("netflix",),
    "now": ("now",),
    "paramount_plus": ("paramount plus", "paramount+"),
    "peacock": ("peacock",),
    "plex": ("plex",),
    "prime": ("amazon prime video", "prime video"),
    "rakuten_tv": ("rakuten tv",),
    "rtl_plus": ("rtl plus", "rtl+"),
    "sky_go": ("sky go",),
    "starz": ("starz",),
    "wow": ("wow",),
    "youtube_premium": ("youtube premium", "youtube"),
    "zdf": ("zdf",),
}
